# docker build -t ai.tencentmusic.com/tme-public/notebook:vscode-ubuntu-gpu-base -f Dockerfile-gpu-base .

FROM ai.tencentmusic.com/tme-public/notebook:vscode-ubuntu-gpu-theia

USER root
# 安装中文，和基础的apt工具包
RUN apt update && apt install -y --force-yes --no-install-recommends vim apt-transport-https gnupg2 ca-certificates-java rsync jq  wget git sysstat dnsutils iputils-ping net-tools curl mysql-client locales sysstat && apt clean

RUN echo "alias ll='ls -alF'" >> ~/.bashrc && \
    echo "alias la='ls -A'" >> ~/.bashrc && \
    echo "alias vi='vim'" >> ~/.bashrc && \
    /bin/bash -c "source ~/.bashrc"

RUN apt install -y libsasl2-dev libpq-dev && rm -f /usr/bin/python && rm -f /usr/local/bin/pip && rm -f /usr/bin/pip && ln -s /usr/local/bin/python3 /usr/bin/python && ln -s /usr/bin/pip3 /usr/bin/pip

# 安装python包
RUN pip3 install --upgrade pip  && pip install gsutil pysnooper kubernetes simplejson sqlalchemy pandas numpy requests flask pymysql ray && \
    rm -rf /tmp/* /var/tmp/* ~/.cache

# 安装内网的工具。 pip源  ubuntu源  l5，北极星之类的
RUN mkdir -p /usr/local/services/ && mkdir -p /data/L5Backup/ && chmod -R 777 /data/L5Backup/ && cd /usr/local/services/ && wget https://docker-76009.sz.gfp.tencent-cloud.com/tlinux/l5_protocol_32os-1.0.tar.gz && tar -zxvf l5_protocol_32os-1.0.tar.gz && rm l5_protocol_32os-1.0.tar.gz
COPY pip.conf /root/.pip/pip.conf
COPY ubuntu-sources.list /etc/apt/sources.list
COPY init.sh /init.sh
COPY ca-certificates.crt /ca-certificates.crt
RUN cat /ca-certificates.crt >> /etc/ssl/certs/ca-certificates.crt
RUN apt update && pip install polaris-python --index-url https://mirrors.cloud.tencent.com/pypi/simple/  --extra-index-url https://mirrors.tencent.com/repository/pypi/tencent_pypi/simple/


